; File: installer/SystemOptimizer.iss
;
; System Optimizer 2.0 - Inno Setup 6 script.
;
; Do not compile this file directly. Run build-installer.ps1, which publishes the
; application, generates the two text files the wizard shows, and then calls ISCC.
; Compiling by hand will fail on the missing generated files, which is deliberate:
; the wizard's README page is derived from README.md and must not be a second copy
; of it that drifts.
;
; Two mistakes worth not repeating, both guarded against below:
;
;   1. UninstallDisplayIcon must point at something that is actually installed.
;      Aiming it at a separate .ico that never made it into the file list leaves
;      Control Panel showing a blank icon. It points at the executable here,
;      which cannot be absent and carries the icon already.
;   2. Without AppMutex, installing over a running copy fails part-way through
;      on a locked file.

#define AppName        "System Optimizer"
#define AppVersion     "2.0.0"
#define AppPublisher   "Mikie Ledingham"
#define AppExeName     "SystemOptimizer.exe"
#define GitHubUser     "https://github.com/MikieLedingham"
#define RepoUrl        GitHubUser + "/SystemOptimizer"

; Paths are relative to this file's folder.
#define SourceExe      "..\src\bin\publish\win-x64\" + AppExeName
#define BuildDir       "build"

[Setup]
; A dedicated AppId for this product. Deliberately not the GUID any earlier
; build used: this installs to its own folder, and an existing older install is
; left alone rather than uninstalled underneath somebody. The two would appear
; separately in Control Panel, which is the safe outcome.
AppId={{6B2B907A-C194-4B85-92CA-9021C41B1B6E}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
VersionInfoVersion={#AppVersion}

; What Control Panel and Settings > Apps show. AppPublisher is the "Publisher"
; column; there is no other source for it.
AppPublisher={#AppPublisher}
AppPublisherURL={#GitHubUser}
AppSupportURL={#RepoUrl}/issues
AppUpdatesURL={#RepoUrl}/releases
AppCopyright=Copyright (C) 2026 {#AppPublisher}. MIT licensed.

DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
; No publisher folder above it. One product, one folder.

; The application is published self-contained win-x64. Saying so stops the
; installer running on a machine that cannot execute what it installs.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Program Files needs elevation, and an elevated installer can also register the
; startup task without a second prompt.
PrivilegesRequired=admin

; Control Panel's icon comes from this value and nothing else. Pointing it at the
; executable - rather than at a separate .ico that has to be remembered in
; [Files] - is what keeps the icon correct.
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName}
; No UninstallDisplaySize here on purpose - Inno computes EstimatedSize from what
; it actually installs. A number written by hand is a number that goes stale.

; Refuse to install over a running copy, and offer to close it. The name is the
; one Program.Main creates; if that string ever changes, change it here too.
AppMutex=Global\SystemOptimizer_SINGLE_INSTANCE_MUTEX

; The wizard's own icon, and the icon shown in the taskbar while it runs.
SetupIconFile=..\src\SO.ico
WizardStyle=modern
WizardSizePercent=110
DisableWelcomePage=no
ShowLanguageDialog=no

; Both generated by build-installer.ps1 from the repository's own README.md and
; LICENSE, so neither can drift from what the project actually says.
LicenseFile={#BuildDir}\LICENSE.txt
InfoBeforeFile={#BuildDir}\README.txt

OutputDir=output
OutputBaseFilename={#AppName} {#AppVersion} Setup
Compression=lzma2/max
SolidCompression=yes
; ~70 MB of self-contained .NET compresses to roughly a third of that.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
; One file. The publish is self-contained and single-file, so there is no runtime
; to install and no dependency to carry.
;
; Note what is NOT here: the Sanity Check guide. It used to ship as guide\index.html
; beside the executable; it is now generated into %APPDATA% when the user asks to
; read it, which is both writable and per-user.
Source: "{#SourceExe}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
; runasoriginaluser matters. Without it the program starts as a child of the
; elevated installer, so the very first launch after installing runs as
; administrator whether or not the user asked for that - and System Optimizer
; deliberately does not auto-elevate. It has its own "restart as administrator"
; route, and the admin-only cleanups say so where they are chosen.
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent runasoriginaluser

; No [Dirs] entry for %APPDATA%\System Optimizer, deliberately. This installer runs
; elevated, so {userappdata} here is the ADMINISTRATOR's profile, not necessarily
; the person who will run the program. The application creates its own folder on
; first run, which is the only moment the right user is known.

[Code]
var
  GitHubCaption: TNewStaticText;
  GitHubLink: TNewStaticText;

procedure OpenGitHub(Sender: TObject);
var
  ErrorCode: Integer;
begin
  ShellExec('open', '{#GitHubUser}', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
end;

{ A real clickable link on the last page, rather than a postinstall checkbox.
  It is built here rather than declared as a [Run] entry
  because a Run entry can only offer a tick box, and a tick box is not a link.
  (Note for anyone editing this file: a comment line may not START with a square
  bracket. Inno reads the first non-blank character of every line, inside [Code]
  as well as outside it, and a leading bracket is taken for a section tag -
  "Invalid section tag" is what that mistake looks like.) }
procedure InitializeWizard();
begin
  GitHubCaption := TNewStaticText.Create(WizardForm);
  GitHubCaption.Parent := WizardForm.FinishedPage;
  GitHubCaption.AutoSize := True;
  GitHubCaption.Caption := 'Updates, the source code and somewhere to report a problem:';

  GitHubLink := TNewStaticText.Create(WizardForm);
  GitHubLink.Parent := WizardForm.FinishedPage;
  { AutoSize, deliberately. Stretching this to the width of the page would make
    the empty space beside the words open a browser too, and a link you can hit
    by clicking nothing is not a link. }
  GitHubLink.AutoSize := True;
  GitHubLink.Caption := 'github.com/MikieLedingham';
  GitHubLink.Cursor := crHand;
  GitHubLink.Font.Color := clBlue;
  GitHubLink.Font.Style := [fsUnderline];
  GitHubLink.OnClick := @OpenGitHub;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  Bottom: Integer;
begin
  if CurPageID = wpFinished then
  begin
    { Anchored to the BOTTOM of the page, not below FinishedLabel.

      Below the label is where the first version put it, and it landed directly
      on top of the "Launch System Optimizer" tick box - the label's height is
      not the bottom of the page's content, because the run list is placed under
      it. Found by installing and looking at the last page, which is the only way
      it could have been found. }
    Bottom := WizardForm.FinishedPage.ClientHeight;

    GitHubLink.Left := WizardForm.FinishedLabel.Left;
    GitHubLink.Top  := Bottom - GitHubLink.Height - ScaleY(8);

    GitHubCaption.Left := WizardForm.FinishedLabel.Left;
    GitHubCaption.Top  := GitHubLink.Top - GitHubCaption.Height - ScaleY(2);
  end;
end;

{ Ask, defaulting to No. The folder holds history\ - the per-run
  manifests that "Restore a previous clean" reads - so removing it silently would
  destroy the one thing in there that cannot be regenerated. Asking puts the
  decision where it belongs without making it the default. }
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    DataDir := ExpandConstant('{userappdata}\{#AppName}');
    if DirExists(DataDir) then
    begin
      if MsgBox('Also remove your System Optimizer settings and cleanup history?'#13#10#13#10
              + DataDir + #13#10#13#10
              + 'This includes the record of previous cleanups, which is what "Restore a '
              + 'previous clean" uses to put files back. Choose No if you might reinstall.',
                mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
